'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),preview=$('ballPreview'),pc=preview.getContext('2d');
const levels=[
 {name:'İlk sıçrayış',width:2600,start:[90,444],platforms:[[0,490,650,70],[740,490,620,70],[1450,490,1150,70],[290,392,150,22],[860,390,180,22],[1130,300,140,22],[1610,390,160,22],[1880,305,160,22],[2170,390,160,22]],spikes:[[515,490,64],[1170,490,70],[1750,490,75],[2070,490,60]],rings:[[355,345],[890,345],[1200,255],[1950,260],[2240,345]],exit:2490},
 {name:'Biraz daha yükseğe',width:2900,start:[90,444],platforms:[[0,490,440,70],[540,490,480,70],[1140,490,590,70],[1840,490,450,70],[2390,490,510,70],[240,395,140,22],[600,390,160,22],[880,300,145,22],[1210,350,150,22],[1490,300,160,22],[1900,390,140,22],[2140,300,150,22],[2470,385,165,22]],spikes:[[670,490,85],[1340,490,100],[2010,490,85],[2610,490,80]],rings:[[305,350],[670,345],[950,255],[1560,255],[2205,255],[2540,340]],exit:2800},
 {name:'Son büyük sıçrayış',width:3180,start:[90,444],platforms:[[0,490,350,70],[470,490,400,70],[1000,490,470,70],[1590,490,440,70],[2160,490,400,70],[2690,490,490,70],[205,390,120,22],[520,350,140,22],[780,260,140,22],[1080,350,130,22],[1340,255,150,22],[1660,350,140,22],[1920,265,130,22],[2220,360,140,22],[2490,270,140,22],[2780,380,130,22]],spikes:[[610,490,100],[1180,490,110],[1750,490,100],[2330,490,105],[2930,490,70]],rings:[[265,345],[850,215],[1150,305],[1410,210],[1720,305],[1990,220],[2555,225],[2845,335]],exit:3090}
];
let levelIndex=0,level,ball,keys={left:false,right:false},state='ready',lives=3,collected=new Set(),camera=0,viewW=960,rotation=0,last=0,accumulator=0,jumpBuffer=0,coyote=0,photo=null,photoVersion=0,flash=0;
const radius=19,STEP=1/120;
const bonusTypes={double:{symbol:'↑↑',name:'Çift zıplama',color:'#c69aff',duration:3},speed:{symbol:'»',name:'Hız',color:'#80dbff',duration:3},ghost:{symbol:'Ø',name:'Dikenler kapalı',color:'#83edbe',duration:2},shield:{symbol:'◇',name:'Kalkan',color:'#a1baff',duration:0}};
const bonusLayouts=[[[180,440,'double'],[460,440,'ghost'],[800,440,'speed'],[610,440,'shield'],[1530,440,'shield']],[[160,440,'double'],[610,440,'ghost'],[395,440,'shield'],[1160,430,'shield'],[1880,440,'speed']],[[155,440,'double'],[555,440,'ghost'],[310,440,'shield'],[1060,440,'shield'],[1640,435,'speed']]];
let powers={double:0,speed:0,ghost:0,shield:false},bonusTaken=new Set(),airJumpUsed=false,invulnerable=0;
function resetPowers(){powers={double:0,speed:0,ghost:0,shield:false};bonusTaken=new Set();airJumpUsed=false;invulnerable=0;powerHUD();}
function powerHUD(){const active=[];for(const key of ['double','speed','ghost'])if(powers[key]>0)active.push(bonusTypes[key].symbol+' '+bonusTypes[key].name+' '+Math.ceil(powers[key])+' sn');if(powers.shield)active.push('◇ Kalkan · 1 darbe + sıvı köprü');$('powers').textContent=active.join('  ·  ')||'Bonus halkaları: ↑↑ çift zıplama · » hız · Ø dikenleri kapat · ◇ kalkan';}
function takeBonus(b,index){bonusTaken.add(index);const type=bonusTypes[b[2]];if(b[2]==='shield')powers.shield=true;else powers[b[2]]=type.duration;if(b[2]==='double')airJumpUsed=false;bursts.push({x:b[0],y:b[1],age:0,life:1,text:type.symbol,color:type.color});$('tip').textContent=type.name+(b[2]==='shield'?' hazır: bir diken darbesini engeller ve boşlukları sıvı köprüyle kapatır.': ' aktif: '+type.duration+' saniye.')+(b[2]==='double'?' Havadayken tekrar zıpla.':'');powerHUD();}
function drawBonuses(t){for(const [i,b] of bonusLayouts[levelIndex].entries()){if(bonusTaken.has(i))continue;const type=bonusTypes[b[2]],bob=motionPreference?.matches?0:Math.sin(t*.003+i)*3;ctx.save();ctx.strokeStyle=type.color;ctx.fillStyle='#13283b';ctx.lineWidth=4;ctx.beginPath();ctx.arc(b[0],b[1]+bob,23,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=type.color;ctx.shadowColor=type.color;ctx.shadowBlur=12;ctx.font='bold 20px sans-serif';ctx.textAlign='center';ctx.fillText(type.symbol,b[0],b[1]+bob+7);ctx.shadowBlur=0;ctx.font='bold 11px sans-serif';ctx.fillText('BONUS',b[0],b[1]-34+bob);ctx.restore();}}

const motionPreference=window.matchMedia?.('(prefers-reduced-motion: reduce)');
let bursts=[],backgroundBits=[],ambientCountdown=2;
const littleMessages=['hop!','✨','bir tur daha','👀','boing','✦','çok iyi','🫧'];
function resetEffects(){bursts=[];backgroundBits=[];ambientCountdown=2;}
function collectEffect(x,y){bursts.push({x,y,age:0,life:motionPreference?.matches?.45:.85});}
function updateEffects(dt){
 bursts=bursts.filter(b=>(b.age+=dt)<b.life);
 backgroundBits=backgroundBits.filter(b=>(b.age+=dt)<b.life);
 if(motionPreference?.matches){backgroundBits=[];return;}
 ambientCountdown-=dt;
 if(ambientCountdown<=0){ambientCountdown=3+Math.random()*2.5;if(backgroundBits.length<2)backgroundBits.push({x:.15+Math.random()*.7,y:110+Math.random()*80,age:0,life:3.5,text:littleMessages[Math.floor(Math.random()*littleMessages.length)],drift:(Math.random()-.5)*12});}
}
function drawBackgroundBits(){ctx.save();ctx.textAlign='center';ctx.font='500 13px "DM Sans", "Segoe UI Emoji", sans-serif';for(const b of backgroundBits){const p=b.age/b.life;ctx.globalAlpha=Math.sin(p*Math.PI)*.32;ctx.fillStyle='#c4c4e5';ctx.fillText(b.text,b.x*viewW+b.drift*b.age,b.y-b.age*5);}ctx.restore();}
function drawCollectEffects(){ctx.save();for(const b of bursts){const p=b.age/b.life,reduce=motionPreference?.matches;ctx.globalAlpha=1-p;ctx.strokeStyle=b.color||'#ffe6a0';ctx.fillStyle=b.color||'#ffe6a0';if(!reduce){ctx.lineWidth=2*(1-p);ctx.beginPath();ctx.arc(b.x,b.y,20+p*26,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4,d=14+p*40,x=b.x+Math.cos(a)*d,y=b.y+Math.sin(a)*d;ctx.fillRect(x-1.5,y-1.5,3*(1-p),3*(1-p));}}ctx.font='bold 17px "Space Grotesk",sans-serif';ctx.textAlign='center';ctx.fillText(b.text||'+1',b.x,b.y-32-(reduce?0:p*25));}ctx.restore();}

function clearKeys(){keys.left=false;keys.right=false;jumpBuffer=0;}
function loadLevel(i){resetEffects();resetPowers();levelIndex=i;level=levels[i];ball={x:level.start[0],y:level.start[1],vx:0,vy:0};collected=new Set();camera=0;rotation=0;lives=3;coyote=0;clearKeys();updateHUD();$('tip').textContent='İpucu: Tüm halkaları topladığında yeşil çıkış kapısı açılır.';}

function liquidGaps(){const ground=level.platforms.filter(p=>p[1]===490&&p[3]>30).sort((a,b)=>a[0]-b[0]);const gaps=[];for(let i=1;i<ground.length;i++){const end=ground[i-1][0]+ground[i-1][2];if(ground[i][0]>end)gaps.push([end,ground[i][0]]);}return gaps;}
function landOnLiquid(oldY){if(!powers.shield||ball.vy<0||oldY+radius>492||ball.y+radius<490)return;for(const [left,right] of liquidGaps())if(ball.x+radius>left&&ball.x-radius<right){ball.y=490-radius;ball.vy=0;coyote=.1;airJumpUsed=false;break;}}
function drawLiquid(t){if(!powers.shield)return;ctx.save();for(const [left,right] of liquidGaps()){ctx.fillStyle='#60dbcf55';ctx.fillRect(left,490,right-left,22);ctx.strokeStyle='#a2fff0';ctx.lineWidth=3;ctx.beginPath();for(let x=left;x<=right;x+=3){const y=490+(motionPreference?.matches?0:Math.sin(x*.08-t*.004)*2);if(x===left)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();ctx.fillStyle='#9bf8e5';ctx.font='bold 10px sans-serif';ctx.textAlign='center';ctx.fillText('SIVI KÖPRÜ',(left+right)/2,529);}ctx.restore();}

function updateHUD(){$('rings').textContent=`${collected.size} / ${level.rings.length}`;$('lives').textContent='● '.repeat(lives).trim();$('levelLabel').textContent=`BÖLÜM 0${levelIndex+1}`;$('levelName').textContent=level.name;}
function modal(title,text,button,overline){$('modalTitle').textContent=title;$('modalText').textContent=text;$('start').textContent=button;$('overline').textContent=overline;$('overlay').hidden=false;$('pause').disabled=true;}
function play(){$('start').blur();if(state==='paused'){state='playing';}else if(state==='complete'){if(levelIndex<levels.length-1)loadLevel(levelIndex+1);else loadLevel(0);state='playing';}else{loadLevel(levelIndex);state='playing';}$('overlay').hidden=true;$('pause').disabled=false;last=0;clearKeys();}
function pause(){if(state!=='playing')return;state='paused';clearKeys();modal('Kısa bir mola.','Hazır olduğunda kaldığın yerden devam et.','DEVAM ET →','ACELEMİZ YOK.');}
function die(){resetEffects();resetPowers();lives--;updateHUD();clearKeys();flash=.4;if(lives<=0){state='over';modal('Bir tur daha?','Fotoğrafın hazır. Şimdi yolu bir kez daha deneyelim.','TEKRAR DENE →','YOLUN SONU DEĞİL.');}else{ball={x:level.start[0],y:level.start[1],vx:0,vy:0};camera=0;coyote=0;$('tip').textContent='Hop! Başlangıca döndün. Topladığın halkalar sende kaldı.';}}
function jump(){if(state==='playing')jumpBuffer=.14;}
function update(dt){if(state!=='playing')return;updateEffects(dt);for(const key of ['double','speed','ghost'])powers[key]=Math.max(0,powers[key]-dt);invulnerable=Math.max(0,invulnerable-dt);powerHUD();flash=Math.max(0,flash-dt);jumpBuffer=Math.max(0,jumpBuffer-dt);coyote=Math.max(0,coyote-dt);const move=Number(keys.right)-Number(keys.left);ball.vx=move*(powers.speed>0?390:270);if(jumpBuffer>0&&(coyote>0||(powers.double>0&&!airJumpUsed))){if(coyote<=0)airJumpUsed=true;ball.vy=-610;jumpBuffer=0;coyote=0;}ball.vy=Math.min(850,ball.vy+1550*dt);const oldY=ball.y;ball.x=Math.max(radius,Math.min(level.width-radius,ball.x+ball.vx*dt));ball.y+=ball.vy*dt;for(const p of level.platforms){if(ball.vy>=0&&oldY+radius<=p[1]+2&&ball.y+radius>=p[1]&&ball.x+radius>p[0]+3&&ball.x-radius<p[0]+p[2]-3){ball.y=p[1]-radius;ball.vy=0;coyote=.1;airJumpUsed=false;}}
 landOnLiquid(oldY);
 rotation+=ball.vx*dt/radius;
 for(const [i,b] of bonusLayouts[levelIndex].entries())if(!bonusTaken.has(i)&&Math.hypot(ball.x-b[0],ball.y-b[1])<radius+23)takeBonus(b,i);
 for(const s of level.spikes){if(powers.ghost<=0&&invulnerable<=0&&ball.x+radius*.65>s[0]&&ball.x-radius*.65<s[0]+s[2]&&ball.y+radius>s[1]-23&&ball.y-radius<s[1]){if(powers.shield){powers.shield=false;invulnerable=1.2;ball.vy=-420;ball.y=s[1]-radius-26;coyote=0;$('tip').textContent='Kalkan darbeyi engelledi!';powerHUD();}else{die();return;}break;}}
 if(ball.y>660){die();return;}
 level.rings.forEach((r,i)=>{if(!collected.has(i)&&Math.hypot(ball.x-r[0],ball.y-r[1])<40){collected.add(i);collectEffect(r[0],r[1]);updateHUD();if(collected.size===level.rings.length)$('tip').textContent='Bütün halkalar sende! Yeşil kapıya ulaş.';}});
 if(Math.abs(ball.x-level.exit)<30&&ball.y>405){if(collected.size===level.rings.length){state='complete';clearKeys();modal(levelIndex===2?'İşte bu, şampiyon!':'Harika sıçrayış!',levelIndex===2?'Üç bölümü de bitirdin. Bu maceranın yüzü sendin.':'Tüm halkaları topladın. Sıradaki bölüm seni bekliyor.',levelIndex===2?'BAŞTAN OYNA →':'SONRAKİ BÖLÜM →','BÖLÜM TAMAMLANDI.');}else $('tip').textContent=`Kapı için ${level.rings.length-collected.size} halka daha toplamalısın.`;}
 camera=Math.max(0,Math.min(level.width-viewW,ball.x-viewW*.34));}
function texture(c,x,y,r,angle){c.save();c.translate(x,y);c.rotate(angle);c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.clip();if(photo){const z=Number($('zoom').value),sx=Number($('offsetX').value),sy=Number($('offsetY').value);const scale=Math.max(2*r/photo.width,2*r/photo.height)*z,w=photo.width*scale,h=photo.height*scale;c.drawImage(photo,-w/2-sx*(w-2*r)/2,-h/2-sy*(h-2*r)/2,w,h);}else{const g=c.createRadialGradient(-r*.35,-r*.4,1,0,0,r*1.3);g.addColorStop(0,'#ffa780');g.addColorStop(.4,'#ff654d');g.addColorStop(1,'#b52635');c.fillStyle=g;c.fillRect(-r,-r,r*2,r*2);c.fillStyle='#ffceaa';c.beginPath();c.ellipse(-r*.3,-r*.42,r*.27,r*.15,-.6,0,Math.PI*2);c.fill();}c.restore();c.strokeStyle=photo?'#fff2d6':'#ffaf82';c.lineWidth=2;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.stroke();}
function drawPreview(){pc.clearRect(0,0,240,240);pc.fillStyle='#0b101866';pc.beginPath();pc.ellipse(120,193,51,8,0,0,Math.PI*2);pc.fill();texture(pc,120,108,65,0);}
function render(t){viewW=canvas.clientWidth/canvas.clientHeight*560;const dpr=Math.min(window.devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.setTransform(canvas.width/viewW,0,0,canvas.height/560,0,0);ctx.fillStyle='#172840';ctx.fillRect(0,0,viewW,560);
 // Functional playfield geometry, with a quiet grid behind it.
 ctx.strokeStyle='#839bbe0c';ctx.lineWidth=1;for(let x=-(camera*.2)%40;x<viewW;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,560);ctx.stroke();}for(let y=0;y<560;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(viewW,y);ctx.stroke();}
 drawBackgroundBits();
 ctx.save();ctx.translate(-camera,0);
 for(const p of level.platforms){ctx.fillStyle='#293d59';ctx.fillRect(...p);ctx.fillStyle='#526b87';ctx.fillRect(p[0],p[1],p[2],5);ctx.fillStyle='#182b43';for(let x=p[0];x<p[0]+p[2];x+=42){ctx.fillRect(x,p[1]+6,2,p[3]-6);}if(p[3]>30){ctx.fillStyle='#344d69';ctx.fillRect(p[0],p[1]+32,p[2],2);}}
 ctx.save();if(powers.ghost>0)ctx.globalAlpha=.16;
 for(const s of level.spikes){ctx.fillStyle='#ff8c88';ctx.strokeStyle='#ffc0a1';for(let x=s[0];x<s[0]+s[2];x+=20){ctx.beginPath();ctx.moveTo(x,s[1]);ctx.lineTo(x+10,s[1]-25);ctx.lineTo(x+20,s[1]);ctx.closePath();ctx.fill();}ctx.fillStyle='#bd5966';ctx.fillRect(s[0],s[1]-4,s[2],4);}
 ctx.restore();drawLiquid(t);drawBonuses(t);
 level.rings.forEach((r,i)=>{if(collected.has(i))return;const bob=Math.sin(t*.002+i)*3;ctx.strokeStyle='#ffd174';ctx.lineWidth=6;ctx.beginPath();ctx.ellipse(r[0],r[1]+bob,17,24,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#fff0b6';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(r[0]-1,r[1]-1+bob,17,24,0,Math.PI,Math.PI*1.6);ctx.stroke();});
 const unlocked=collected.size===level.rings.length;ctx.fillStyle=unlocked?'#82debc':'#3d6a66';ctx.fillRect(level.exit-26,412,52,78);ctx.fillStyle='#102f38';ctx.fillRect(level.exit-19,420,38,70);ctx.fillStyle=unlocked?'#a6fce0':'#689990';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText(unlocked?'ÇIKIŞ':'KİLİTLİ',level.exit,398);ctx.fillStyle=unlocked?'#82debc':'#436967';ctx.fillRect(level.exit+7,452,5,5);drawCollectEffects();texture(ctx,ball.x,ball.y,radius,rotation);if(powers.shield||invulnerable>0){ctx.strokeStyle= powers.shield?'#a1baff':'#ecf3ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(ball.x,ball.y,radius+7,0,Math.PI*2);ctx.stroke();}ctx.restore();if(flash>0){ctx.fillStyle=`rgba(255,99,84,${flash*.3})`;ctx.fillRect(0,0,viewW,560);}}
function frame(time){if(!last)last=time;accumulator+=Math.min((time-last)/1000,.05);last=time;while(accumulator>=STEP){update(STEP);accumulator-=STEP;}render(time);requestAnimationFrame(frame);}
$('start').onclick=play;$('pause').onclick=pause;$('restart').onclick=()=>{$('restart').blur();loadLevel(levelIndex);state='playing';$('overlay').hidden=true;$('pause').disabled=false;};
const keymap={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'&&e.target.tagName==='BUTTON')return;if(keymap[e.key]){e.preventDefault();if(state==='playing')keys[keymap[e.key]]=true;}if(['ArrowUp','w','W',' '].includes(e.key)){e.preventDefault();if(!e.repeat)jump();}if(e.key==='Escape'||e.key==='p'||e.key==='P'){if(state==='playing')pause();else if(state==='paused')play();}});document.addEventListener('keyup',e=>{if(keymap[e.key])keys[keymap[e.key]]=false;});
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(k==='jump')jump();else if(state==='playing')keys[k]=true;});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{if(k!=='jump')keys[k]=false;});});
window.addEventListener('blur',()=>{clearKeys();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearKeys();pause();}});
$('photo').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(state==='playing')pause();const version=++photoVersion;$('photoStatus').textContent='Fotoğraf hazırlanıyor…';if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)||file.size>15*1024*1024){$('photoStatus').textContent='15 MB altında bir JPG, PNG, WebP veya AVIF seç.';e.target.value='';return;}const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(version!==photoVersion)return;if(img.naturalWidth*img.naturalHeight>50e6)throw Error('large');const out=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight));out.width=Math.max(1,Math.round(img.naturalWidth*scale));out.height=Math.max(1,Math.round(img.naturalHeight*scale));out.getContext('2d').drawImage(img,0,0,out.width,out.height);photo=out;$('zoom').value='1';$('offsetX').value='0';$('offsetY').value='0';$('crop').hidden=false;$('remove').disabled=false;$('photoLabel').textContent='↻ Farklı fotoğraf seç';$('ballName').textContent='Senin topun';$('photoStatus').textContent='Hazır! Ayarlarla fotoğrafını ortalayabilirsin.';drawPreview();}catch{$('photoStatus').textContent='Bu fotoğraf açılamadı. Daha küçük bir JPG veya PNG dene.';}finally{URL.revokeObjectURL(url);e.target.value='';}};
for(const id of ['zoom','offsetX','offsetY'])$(id).oninput=drawPreview;
$('remove').onclick=()=>{photoVersion++;photo=null;$('photo').value='';$('zoom').value='1';$('offsetX').value='0';$('offsetY').value='0';$('remove').disabled=true;$('photoLabel').textContent='＋ Fotoğraf yükle';$('crop').hidden=true;$('ballName').textContent='Klasik kırmızı';$('photoStatus').textContent='';drawPreview();};
loadLevel(0);drawPreview();requestAnimationFrame(frame);


